#!/usr/bin/env bash

cd ukf-meta

echo "Commit comments should be the same, hashes different:"
git branch --list --verbose master public

echo
echo "Number of revisions should be different:"
echo "   master: " `git log --oneline master | wc -l`
echo "   public: " `git log --oneline public | wc -l`

# End
