#!/usr/bin/env bash

cd ukf-meta

git checkout -b public

#
# Remove git svn metadata from commit messages, and
# all empty commits.
#
git filter-branch \
	--msg-filter 'sed -e "/^git-svn-id:/d"' \
	--prune-empty \
	-- \
	HEAD

# End
