#!/usr/bin/env bash

#
# Initialize the ukf-meta directory as a git-svn clone of the the private
# version of the UK federation's metadata repository.
#

# Delete any previous attempt
rm -rf ukf-meta

# Initialise repository
git clone git@repo.infr.ukfederation.org.uk:ukf/ukf-meta.git
cd ukf-meta
git config push.default upstream

# End
