#!/usr/bin/env bash

#
# Reinitialize an existing ukf-meta directory where possible
# to take account of changes.
#

cd ukf-meta

git config svn.authorsfile `cd ..;pwd`/authors
git config push.default upstream

#
# Configure the set of files and directories to be ignored by
# git svn operations by constructing a regular expression
# to match them. This should not change in the lifetime of the
# repository except to exclude files which have never previously
# been committed.
#
# Construct the regular expression by combining a number of
# smaller ones.
#
XBUILD="build/(expiry_whitelist|extra_addresses|list)"
XMDX="mdx/(int_edugain/(entity|verify)-blacklist)"
XTOOLS="tools/(apache-ant|mda|samlsign|xmltool)"
XTOP="OpenAthens|certs|endorsed|entities|lib|src|test|trunk|xalan"
XXML="xml/(entities|master|members|ukfed|sdss)"

git config svn-remote.svn.ignore-paths \
	"^trunk/($XBUILD|$XMDX|$XTOOLS|$XTOP|$XXML)"

# End
