#!/usr/bin/env bash

cd ukf-meta

# Switch back to the master branch
git checkout master

# Pull in any new material
git pull --ff-only origin

#
# Run the branch update process inside a Docker container.
#
cd ..
docker run -it --rm -v `pwd`:/home/user git-1.8 ./do_filter

# End
